defmodule Axigbe.Repo.Migrations.MakeBusinessMandatoryOnProduct do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:products) do
      remove :owner_id
      modify :business_id, :uuid, null: false
    end
  end

  def down do
    alter table(:products) do
      modify :business_id, :uuid, null: true

      add :owner_id,
          references(:users,
            column: :id,
            name: "products_owner_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end
end
