defmodule Axigbe.Repo.Migrations.AddArrondissementToBusiness do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:business_addresses) do
      add :arrondissement, :text, null: false
    end
  end

  def down do
    alter table(:business_addresses) do
      remove :arrondissement
    end
  end
end
