defmodule Axigbe.Repo.Migrations.UpdateBusisessSubCategoryRelationship do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:business_sub_categories) do
      remove :business_id
    end
  end

  def down do
    alter table(:business_sub_categories) do
      add :business_id,
          references(:businesses,
            column: :id,
            name: "business_sub_categories_business_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end
end
