defmodule Axigbe.Repo.Migrations.AddAddressToBusiness do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:business_addresses, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :country, :text, null: false
      add :department, :text, null: false
      add :commune, :text, null: false
      add :city, :text, null: false
      add :neighbourhood, :text, null: false
      add :location_desciption, :text, null: false
      add :long, :float
      add :lat, :float

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :business_id,
          references(:businesses,
            column: :id,
            name: "business_addresses_business_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:business_addresses, "business_addresses_business_id_fkey")

    drop table(:business_addresses)
  end
end
