defmodule Axigbe.Repo.Migrations.AddImagesToProducts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:products) do
      add :images, {:array, :text}, null: false
    end

    alter table(:business_categories) do
      remove :business_id
    end
  end

  def down do
    alter table(:business_categories) do
      add :business_id,
          references(:businesses,
            column: :id,
            name: "business_categories_business_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:products) do
      remove :images
    end
  end
end
