defmodule Axigbe.Repo.Migrations.AddProductPriceAsMoneyType do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:products) do
      add :price, :money_with_currency
    end
  end

  def down do
    alter table(:products) do
      remove :price, :float
    end
  end
end
