defmodule Axigbe.Repo.Migrations.MakeImgOptionalOnProduct do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:products) do
      modify :images, {:array, :text}, null: true
    end

    alter table(:businesses) do
      add :avatar, :text,
        null: false,
        default:
          "https://gravatar.com/avatar/9474ded9f72bb55143599151b9356a9f?s=400&d=robohash&r=x"

      add :banner, :text,
        null: false,
        default:
          "https://images.unsplash.com/photo-1726533870778-8be51bf99bb1?q=80&w=1674&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    end
  end

  def down do
    alter table(:businesses) do
      remove :banner
      remove :avatar
    end

    alter table(:products) do
      modify :images, {:array, :text}, null: false
    end
  end
end
