defmodule Axigbe.Repo.Migrations.AddCategoryToProduct do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:products) do
      add :category_id, :uuid, null: false
    end

    create table(:product_categories, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:products) do
      modify :category_id,
             references(:product_categories,
               column: :id,
               name: "products_category_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:product_categories) do
      add :name, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:product_categories, [:name],
             name: "product_categories_unique_product_category_index"
           )
  end

  def down do
    drop_if_exists unique_index(:product_categories, [:name],
                     name: "product_categories_unique_product_category_index"
                   )

    alter table(:product_categories) do
      remove :updated_at
      remove :inserted_at
      remove :name
    end

    drop constraint(:products, "products_category_id_fkey")

    alter table(:products) do
      modify :category_id, :uuid
    end

    drop table(:product_categories)

    alter table(:products) do
      remove :category_id
    end
  end
end
