defmodule Axigbe.Repo.Migrations.CorrectLocationDescriptionOnBusinessAddress do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:business_addresses), :location_desciption, to: :location_description

    alter table(:business_addresses) do
      modify :location_description, :text
    end
  end

  def down do
    alter table(:business_addresses) do
      modify :location_desciption, :text
    end

    rename table(:business_addresses), :location_description, to: :location_desciption
  end
end
