defmodule Axigbe.Repo.Migrations.MakeBusinessOwnerMandatoryAddPriceToProduct do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:products) do
      add :price, :float, null: false
    end

    alter table(:businesses) do
      modify :owner_id, :uuid, null: false
    end
  end

  def down do
    alter table(:businesses) do
      modify :owner_id, :uuid, null: true
    end

    alter table(:products) do
      remove :price
    end
  end
end
