defmodule Axigbe.Repo.Migrations.UpdateOnProductPrice do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:products) do
      modify :price, :money_with_currency, null: true
    end
  end

  def down do
    alter table(:products) do
      modify :price, :money_with_currency, null: false
    end
  end
end
