defmodule Axigbe.Repo.Migrations.AddPriceOnDemandForProduct do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:products) do
      add :price_on_demand?, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:products) do
      remove :price_on_demand?
    end
  end
end
