defmodule Axigbe.Repo.Migrations.CreateBusinessesProductsBusinessCategoriesBusinessSubCategriesBusinessReviewsProductReviews do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:products, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :description, :text, null: false
      add :is_service?, :boolean, null: false, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id,
          references(:users,
            column: :id,
            name: "products_owner_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :business_id, :uuid
    end

    create table(:product_reviews, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :comment, :text, null: false
      add :rating, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :product_id,
          references(:products,
            column: :id,
            name: "product_reviews_product_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:businesses, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:products) do
      modify :business_id,
             references(:businesses,
               column: :id,
               name: "products_business_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:businesses) do
      add :name_id, :text, null: false
      add :name, :text, null: false
      add :description, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id,
          references(:users,
            column: :id,
            name: "businesses_owner_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:businesses, [:name_id], name: "businesses_unique_business_name_id_index")

    create table(:business_sub_categories, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :business_id,
          references(:businesses,
            column: :id,
            name: "business_sub_categories_business_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :business_category_id, :uuid
    end

    create table(:business_reviews, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :comment, :text, null: false
      add :rating, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :business_id,
          references(:businesses,
            column: :id,
            name: "business_reviews_business_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:business_categories, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:business_sub_categories) do
      modify :business_category_id,
             references(:business_categories,
               column: :id,
               name: "business_sub_categories_business_category_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:business_sub_categories, [:name],
             name: "business_sub_categories_unique_business_sub_category_index"
           )

    alter table(:business_categories) do
      add :name, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :business_id,
          references(:businesses,
            column: :id,
            name: "business_categories_business_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:business_categories, [:name],
             name: "business_categories_unique_business_category_index"
           )

    create table(:business_business_sub_categories, primary_key: false) do
      add :business_id,
          references(:businesses,
            column: :id,
            name: "business_business_sub_categories_business_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :sub_category_id,
          references(:business_sub_categories,
            column: :id,
            name: "business_business_sub_categories_sub_category_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false
    end
  end

  def down do
    drop constraint(
           :business_business_sub_categories,
           "business_business_sub_categories_business_id_fkey"
         )

    drop constraint(
           :business_business_sub_categories,
           "business_business_sub_categories_sub_category_id_fkey"
         )

    drop table(:business_business_sub_categories)

    drop_if_exists unique_index(:business_categories, [:name],
                     name: "business_categories_unique_business_category_index"
                   )

    drop constraint(:business_categories, "business_categories_business_id_fkey")

    alter table(:business_categories) do
      remove :business_id
      remove :updated_at
      remove :inserted_at
      remove :name
    end

    drop_if_exists unique_index(:business_sub_categories, [:name],
                     name: "business_sub_categories_unique_business_sub_category_index"
                   )

    drop constraint(:business_sub_categories, "business_sub_categories_business_category_id_fkey")

    alter table(:business_sub_categories) do
      modify :business_category_id, :uuid
    end

    drop table(:business_categories)

    drop constraint(:business_reviews, "business_reviews_business_id_fkey")

    drop table(:business_reviews)

    drop constraint(:business_sub_categories, "business_sub_categories_business_id_fkey")

    drop table(:business_sub_categories)

    drop_if_exists unique_index(:businesses, [:name_id],
                     name: "businesses_unique_business_name_id_index"
                   )

    drop constraint(:businesses, "businesses_owner_id_fkey")

    alter table(:businesses) do
      remove :owner_id
      remove :updated_at
      remove :inserted_at
      remove :description
      remove :name
      remove :name_id
    end

    drop constraint(:products, "products_business_id_fkey")

    alter table(:products) do
      modify :business_id, :uuid
    end

    drop table(:businesses)

    drop constraint(:product_reviews, "product_reviews_product_id_fkey")

    drop table(:product_reviews)

    drop constraint(:products, "products_owner_id_fkey")

    drop table(:products)
  end
end
