defmodule Axigbe.Repo.Migrations.UpdateProductPrice do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:products) do
      remove :price

    end
  end

  def down do
    alter table(:products) do
      add :price, :float, null: false
    end
  end
end
